crisp: annotate and enforce MVIR.node argument type
this converts "AttributeError: 'NoneType' object has no attribute 'raw'" into an assertion failure in Workflow.cc_custom, which is easier to understand